### ISSUE TITLE
Newbie-How to execute? 

### ISSUE THREAD

**Issue by pemagrg1** [kasramp/Translate-WebApp#2]
Hi! am new here...
May i know how to run this project? 
like if i have to install anything or run through ubuntu terminal?

**Comment by kasramp** [comment]
The first thing you need to do is to install Apache and PHP. You can refer here:
https://www.unixmen.com/how-to-install-lamp-stack-on-ubuntu-16-04/
After that clone the project `git clone https://github.com/kasramp/Translate-WebApp.git`.
Then in terminal navigate to the project directory and lastly run `deploy.sh` script.
`sudo ./deploy.sh`.
If you open browser and type `localhost/Translate/` should be able to see the app.
